### ISSUE TITLE
Need to add in Halo stars and kinematics. 

### ISSUE THREAD

**Issue by ctheissen** [ctheissen/LoKi#1]
Just throwing these out since the numbers are so small, but it would be nice to actually simulate the handful we see.

**Comment by dhitals** [comment]
Yeah, it would be good to simulate **v**, especially as you go further out into the Galaxy. You will need to finetune the rejection function  (i.e., change the normaliztion) to make sure that resampling velocities is efficient and does not take an inordinate amount of time.

I think M. Juric et al. (2008) and W. Brown et al. (2009) have some information on halo velocity dispersions.

**Comment by ctheissen** [comment]
Used the results of Bond et al. 2010 to add in velocity dispersions for halo stars.
